name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
      - Containers/dbatoolslifehacks/dockerfile
      - Containers/dbatoolslifehacks2/dockerfile
      - Profile/profile.ps1
    
  pull_request:
    branches: [ main ]
    paths:
      - Containers/dbatoolslifehacks/dockerfile
      - Containers/dbatoolslifehacks2/dockerfile
      - Profile/profile.ps1
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push First Container
        uses: docker/build-push-action@v2
        with:
          push: true
          context: Containers/dbatoolslifehacks/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbatoolslifehacks:latest
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbatoolsprecon:${{ steps.bump.outputs.new_tag }},${{ secrets.DOCKERHUB_USERNAME }}/dbatoolsprecon:latest
      -
        name: Build and push Sql Instance 2
        uses: docker/build-push-action@v2
        with:
          push: true
          context: Containers/dbatoolslifehacks2/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbatoolslifehacks2:latest
      -
        name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2
        with:
          author_name: jpomfret
          author_email: jpomfret7@gmail.com 
          message: 'new container images!'